## Quiz

In [1]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)
print(b.shape)


(2, 3)


In [2]:
import numpy as np
np.sin(np.pi / 2)


1.0

In [5]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)


[5 7 9]


In [6]:
import numpy as np
a = np.array([3, 1, 2])
print(np.sort(a))


[1 2 3]


In [7]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A, B))


[[19 22]
 [43 50]]
