In [9]:
import numpy as np

arr=np.random.randint(1,100,size=(10,5)) # sample-10, feature - 5

In [10]:
arr.shape

(10, 5)

In [13]:
b=arr.reshape(5,10)
b.shape


(5, 10)

In [16]:
b.ndim


2

In [23]:
b

array([[86,  4, 64, 82, 80, 84, 73, 67, 56, 51],
       [77, 63, 94, 93, 19, 26, 30, 50, 11, 97],
       [65, 29, 80, 25, 63,  7, 37, 39, 36, 14],
       [17, 69, 28, 95, 29, 37, 54,  3, 90, 18],
       [81, 13, 24, 85, 23, 13, 45, 46, 32, 69]])

In [24]:
flatten =b.flatten()
print(flatten.ndim)
flatten



1


array([86,  4, 64, 82, 80, 84, 73, 67, 56, 51, 77, 63, 94, 93, 19, 26, 30,
       50, 11, 97, 65, 29, 80, 25, 63,  7, 37, 39, 36, 14, 17, 69, 28, 95,
       29, 37, 54,  3, 90, 18, 81, 13, 24, 85, 23, 13, 45, 46, 32, 69])

In [28]:
column_wise_flattening=np.ravel(b,order='F')
print(column_wise_flattening)

row_wise_flattening=np.ravel(b,order='C') #flatten er poriborte row wise evabe kora jay
print(row_wise_flattening)

[86 77 65 17 81  4 63 29 69 13 64 94 80 28 24 82 93 25 95 85 80 19 63 29
 23 84 26  7 37 13 73 30 37 54 45 67 50 39  3 46 56 11 36 90 32 51 97 14
 18 69]
[86  4 64 82 80 84 73 67 56 51 77 63 94 93 19 26 30 50 11 97 65 29 80 25
 63  7 37 39 36 14 17 69 28 95 29 37 54  3 90 18 81 13 24 85 23 13 45 46
 32 69]


In [29]:
a=np.random.randint(1,10,size=(2,3))
b=np.random.randint(20,30,size=(1,5))

## Quiz

In [1]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)
print(b.shape)


(2, 3)


In [2]:
import numpy as np
np.sin(np.pi / 2)


1.0

In [5]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)


[5 7 9]


In [6]:
import numpy as np
a = np.array([3, 1, 2])
print(np.sort(a))


[1 2 3]


In [7]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A, B))


[[19 22]
 [43 50]]
