In [1]:
arr=[1,2,3]
print(arr*5)

arr=[x*5 for x in arr]
print(arr)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[5, 10, 15]


In [42]:
import numpy as np

arr1 =np.array([1,2,3])
arr1=arr1*5
print(arr1)

[ 5 10 15]


## Ndarray

In [44]:
import numpy as np

# 1d array
arr1=np.array([1,2,3,4,5])
print(type(arr1))
print(arr1.ndim)


<class 'numpy.ndarray'>
1


In [ ]:
import numpy as np

#1d array
arr1=np.array([1,2,3,4,5,6])
print(type(arr1))
print(arr1.ndim)# number of dimension


#2d array
arr2=np.array([[1,2,3,6],# 1d
              [4,5,6,7] #2d
              ])
print(arr2.ndim)


#3d array 
arr3 = np.array([
    #1st floor
    [ [1,2,3], # row1
      [4,5,6]  ], #row2 

    #2nd floor

     [[1,2,3], # row1
      [4,5,6]  ], #row2  


    #3rd floor
      [[1,2,3], # row1
      [4,5,6]  ] #row2  
   
])

print(type(arr3))
print(arr3.ndim)

<class 'numpy.ndarray'>
1
2
<class 'numpy.ndarray'>
3


## Array attributes

In [ ]:
# dimension 
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim) 


#shape 
print(arr1.shape)
print(arr2.shape)
print(arr3.shape) 


#data type 
print(arr1.dtype)# data type
print(arr2.dtype)
print(arr3.dtype)


#size 
print(arr1.size)
print(arr2.size)
print(arr3.size)

1
2
3
(6,)
(2, 4)
(3, 2, 3)
int64
int64
int64
6
8
18


## ndarray data type

In [56]:
arr =np.array([1,2,3])
print(arr.dtype)

arr=np.array([1.5,2.5,3.2])
print(arr.dtype)


int64
float64


In [73]:
# upcasted to float 
arr = np.array([1,2,3.2]) # NumPy=np
print(arr.dtype) 

#upcasted to string
arr = np.array([1,2,3.2,'hello']) 
print(arr.dtype) 


arr = np.array([1,True,3.25,'hello',]) 
print(arr.dtype) 

float64
<U32
<U32


## selecting a data type for an array

In [66]:
arr = np.array([1,2,3],dtype=np.int8)# Int a convert korbe
print(arr.dtype)
print(arr)

arr = np.array([1,2,3.6],dtype=np.float128)# Int a convert korbe
print(arr.dtype)
print(arr)


arr = arr.astype(np.int32)  #type change korar method
print(arr.dtype)

arr=np.array([1,2,3])
print(arr.dtype)
arr=arr.astype(np.int16)
print(arr.dtype)


#error
arr = np.array([1,2,3.2,'hello'],dtype=np.float64) #float a convert korbe . but ekta string thaker karone float hobe na. tai error 

int8
[1 2 3]
float128
[1.  2.  3.6]
int32
int64
int16


ValueError: could not convert string to float: 'hello'

## ndarray creation from existing data

In [71]:
#list 
lst = [10,20,30,40,40.5]### N-dimensional array--> ndarray
arr=np.array(lst)
print(arr)
print(type(arr))
print(arr.dtype)


lst = [10,20,30,40,40.5] 
arr = np.array(lst, dtype=np.int32) 
print(arr) 
print(type(arr)) 
print(arr.dtype) 


mixed_lst = [10, True , 'Hello' ]
arr = np.array(mixed_lst) 
print(arr) 
print(type(arr)) 
print(arr.dtype) 


matrix = [ [1,2,3], # row1
           [4,5,6] #row2
                ]

arr = np.array(matrix) 

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim) 

[10.  20.  30.  40.  40.5]
<class 'numpy.ndarray'>
float64
[10 20 30 40 40]
<class 'numpy.ndarray'>
int32
['10' 'True' 'Hello']
<class 'numpy.ndarray'>
<U21
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64
(2, 3)
2


In [78]:
#tuple 

tpl = (10,20,30) 

arr=np.array(tpl)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

# dui vabe kora jay . same

tpl = (10,20,30) 

arr = np.array(tpl,dtype=np.int32)
print(arr.dtype) 
arr = arr.astype(np.int16)
print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim) 

[10 20 30]
<class 'numpy.ndarray'>
int64
(3,)
1
int32
[10 20 30]
<class 'numpy.ndarray'>
int16
(3,)
1


In [74]:
#set 

st = { 1, 2, 3 }

arr = np.array(list(st))
print(arr.dtype) 

arr = arr.astype(np.int16)
print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim) 

int64
[1 2 3]
<class 'numpy.ndarray'>
int16
(3,)
1


In [11]:
# dictionary 

dc = { 'a' : 10 , 'b' : 20 , 'c' :30 }

keys = dc.keys()
values = dc.values()
items = dc.items()

In [12]:
#keys to ndarray
arr = np.array(list(keys))
print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)


['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
(3,)
1
3


In [13]:
#values to ndarray
arr = np.array(list(values))
print(arr) 
arr = arr.astype(np.int16)
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[10 20 30]
<class 'numpy.ndarray'>
int16
(3,)
1
3


In [14]:
#items to ndarray
arr = np.array(list(items))
print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
<U21
(3, 2)
2
6


## Creating ndarray from scratch

In [15]:
# np.zeros

arr = np.zeros((2,3),dtype=np.int8)

# print(arr) 
# print(type(arr)) 
# print(arr.dtype) 
# print(arr.shape) 
# print(arr.ndim)
# print(arr.size)

arr = np.zeros_like(arr3) ## arr3 shape same 
print(arr)
print(arr.shape) 

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
(3, 2, 3)


In [16]:
#np.ones

arr = np.ones((3,4,3),dtype=np.int8)

# print(arr) 
# print(type(arr)) 
# print(arr.dtype) 
# print(arr.shape) 
# print(arr.ndim)
# print(arr.size)


arr = np.ones_like(arr3) ## arr3 shape same 
print(arr)
print(arr.shape) 


[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(3, 2, 3)


In [17]:
#np.empty
arr = np.empty((4,3),dtype=np.int8)

# print(arr) 
# print(type(arr)) 
# print(arr.dtype) 
# print(arr.shape) 
# print(arr.ndim)
# print(arr.size)

arr = np.empty_like(arr3) ## arr3 shape same 
print(arr)
print(arr.shape) 

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(3, 2, 3)


In [18]:
#np.full 

arr = np.full((4,3),np.inf)

# print(arr) 
# print(type(arr)) 
# print(arr.dtype) 
# print(arr.shape) 
# print(arr.ndim)
# print(arr.size)


arr = np.full_like(arr3,np.inf,dtype=np.float64) 

print(arr)
print(arr.shape)
print(arr.dtype)

[[[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]]
(3, 2, 3)
float64


## array creation with random values

In [19]:
# np.random.rand(shape) 

arr = np.random.rand(2,3) # 0 ->1 

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[[0.37512965 0.79898045 0.91400675]
 [0.78276265 0.0305652  0.31241807]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6


In [20]:
# np.random.randint(start,end, shape) 

arr = np.random.randint(1,10 , (2,3))  

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)


[[7 2 4]
 [7 2 5]]
<class 'numpy.ndarray'>
int64
(2, 3)
2
6


In [21]:
# np.random.uniform(start,end, shape) 

arr = np.random.uniform(50,100, (3,3,4))   

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)


[[[87.04088813 87.77958218 60.00306604 82.90729526]
  [74.95949521 98.70738514 58.81654547 73.11842172]
  [60.84354451 71.72844699 87.98410391 61.26629295]]

 [[93.24744101 53.06840695 53.68639357 77.74112258]
  [52.85265492 97.56163306 51.42035474 60.06344053]
  [75.73621628 96.83043108 65.23543647 53.17686992]]

 [[72.17285303 87.71464712 62.75942089 84.59231565]
  [62.08422868 84.9253128  60.2220991  82.55277077]
  [73.61573874 74.82313992 83.81832615 60.76264549]]]
<class 'numpy.ndarray'>
float64
(3, 3, 4)
3
36


## array creation with range functions


In [22]:
# np.arange(first , end , step ) -> similar to range function 

arr = np.arange(1 , 10 ,1 )
mat = arr.reshape(3,3) 

print(arr) 
print(mat) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
(9,)
1
9


In [23]:
# np.linspace(start , end(included) , koita) 

arr = np.linspace(0, 4 ,6)


print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[0.  0.8 1.6 2.4 3.2 4. ]
<class 'numpy.ndarray'>
float64
(6,)
1
6


In [24]:
# np.logspace(start , end(included) , koita ) 

arr = np.logspace(0 , 4 ,6, base =2) 

print(arr)

[ 1.          1.74110113  3.03143313  5.27803164  9.18958684 16.        ]


## creating matrix for Linear algebra

In [25]:
diagonal_matrix = np.diag([1,2,3,4])

print(diagonal_matrix)
print(diagonal_matrix.shape)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
(4, 4)


In [26]:
# identity matrix 

identity_mat = np.eye(4)
# print(identity_mat)
# print(identity_mat.shape)


# np.eye(row , column,k) 

mat = np.eye(3,4)
print(mat)

mat = np.eye(3,4,1)
print(mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## indexing and slicing

In [27]:
#indexing 

print(arr1)
print(arr2)

# arr1[2] = 100 

# print(arr1)
arr2[0][2]= 100

print(arr2)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[  1   2 100]
 [  4   5   6]]


In [28]:
#slicing 
#1d = arr[start:end:step] 

arr1_mod = arr1[1:4].copy()
arr1[1] = 2


arr1_mod[2] = 200
print(arr1_mod)
print(arr1)

[  2   3 200]
[1 2 3 4 5]


In [29]:
#2d slicing 
# arr[ row_start : row_end : step , column_start : column_end : step ]

# print(arr2) 

#getting a row 

row_0 = arr2[0:1 ,]

row_1= arr2[1: , ]

# print(row_0)
# print(row_1)


#getting a column 

col_0 = arr2[:: ,0:1]
col_1 = arr2[::,1:2]

print(col_0)
print(col_1)

#getting a portion 


portion = arr2[:: , 0:2] 

print(portion)

[[1]
 [4]]
[[2]
 [5]]
[[1 2]
 [4 5]]


## Advanced Indexing

In [30]:
lst = np.array([ 10 , 20 ,30 ,40 ]) 

values = lst[[0,3,1]]

print(values)

[10 40 20]


In [31]:
print(arr2)
print(arr2[[0,1] , [1,2]])

# boolean kono kichu diye
print(arr2[arr>1])
arr2[arr2>2] = 0 

print(arr2)

[[  1   2 100]
 [  4   5   6]]
[2 6]


IndexError: boolean index did not match indexed array along dimension 0; dimension is 2 but corresponding boolean dimension is 6

In [32]:
print(arr2)

[[  1   2 100]
 [  4   5   6]]


In [33]:
arr  = np.array([[10,20,30] , [100,200,300] ] )

# iteration 
print(arr3)
for i in np.nditer(arr3):
    print(i)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
1
2
3
4
5
6
1
2
3
4
5
6
1
2
3
4
5
6


In [34]:
arr = np.array([1, 2, 3])
print(arr.ndim)


1


In [35]:
arr = np.full((2,2), np.inf)
print(arr)

[[inf inf]
 [inf inf]]


In [36]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr[1:4] = 0
print(arr)


[1 0 0 0 5]
