In [3]:
import numpy as np

arr=np.random.randint(1,100,size=(10,5)) # sample-10, feature - 5

In [4]:
arr.shape

(10, 5)

In [5]:
b=arr.reshape(5,10)
b.shape


(5, 10)

In [6]:
b.ndim


2

In [7]:
b

array([[65, 91,  9, 87, 79, 96, 38, 61, 88, 13],
       [91, 98, 60, 80, 20, 73, 84, 96,  3,  5],
       [ 1, 76, 64,  1, 86, 74, 97, 84, 75, 28],
       [64, 43,  3, 45, 59, 87, 83, 43, 23, 35],
       [12, 42, 90, 93, 95, 18, 14, 82, 16, 78]])

In [8]:
flatten =b.flatten()
print(flatten.ndim)
flatten



1


array([65, 91,  9, 87, 79, 96, 38, 61, 88, 13, 91, 98, 60, 80, 20, 73, 84,
       96,  3,  5,  1, 76, 64,  1, 86, 74, 97, 84, 75, 28, 64, 43,  3, 45,
       59, 87, 83, 43, 23, 35, 12, 42, 90, 93, 95, 18, 14, 82, 16, 78])

In [9]:
column_wise_flattening=np.ravel(b,order='F')
print(column_wise_flattening)

row_wise_flattening=np.ravel(b,order='C') #flatten er poriborte row wise evabe kora jay
print(row_wise_flattening)

[65 91  1 64 12 91 98 76 43 42  9 60 64  3 90 87 80  1 45 93 79 20 86 59
 95 96 73 74 87 18 38 84 97 83 14 61 96 84 43 82 88  3 75 23 16 13  5 28
 35 78]
[65 91  9 87 79 96 38 61 88 13 91 98 60 80 20 73 84 96  3  5  1 76 64  1
 86 74 97 84 75 28 64 43  3 45 59 87 83 43 23 35 12 42 90 93 95 18 14 82
 16 78]


In [10]:
a=np.random.randint(1,10,size=(2,3))
b=np.random.randint(20,30,size=(2,3))

print(a)
print(b)

[[7 9 9]
 [4 1 2]]
[[24 21 24]
 [23 29 23]]


## Concatenate

In [11]:
con_row = np.concatenate((a,b),axis=0) # row wise
print(con_row)
print('\n')

con_col = np.concatenate((a,b), axis = 1) # column wise 
print(con_col)

[[ 7  9  9]
 [ 4  1  2]
 [24 21 24]
 [23 29 23]]


[[ 7  9  9 24 21 24]
 [ 4  1  2 23 29 23]]


In [12]:
# error 

# row wise concetanate korar shomoi column same thakbe 
# col wise concat korar shomoi row ta same thakte hobe 

x = np.random.randint(1 ,10 , size =(2,3))
y = np.random.randint(1 ,10 , size =(1,3))

r = np.concatenate((x,y),axis =0 ) # row
print(r)
r = np.concatenate((x,y),axis =1 ) # col
print(r)

[[3 1 8]
 [2 3 9]
 [1 3 9]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [13]:
# transpose 

mat = np.array([[10,20,30],
                [30,40,50]
               ])

transpose = mat.T

print(transpose) 

[[10 30]
 [20 40]
 [30 50]]


In [14]:
# array split 

a = np.random.randint(1 ,10 , size =(10,))
print(a)
splitted_array = np.array_split(a,3) 

print(splitted_array)

# split -> equal division 
splitted_array = np.split(a,3) 

[3 7 2 4 6 1 4 1 1 5]
[array([3, 7, 2, 4]), array([6, 1, 4]), array([1, 1, 5])]


ValueError: array split does not result in an equal division

## arithmetic operator and mathematical functions

In [ ]:
# faster for vectorization

x = np.array([ 10 , 8 , 30 , 100 ])
y = np.array([ 2 , 3 ,4  ,5 ]) 

add = np.add(x,y) 
print(add)

sub = x-y 
print(sub)

mul = x*y 
print(mul) 

div = x/y 
print(div) 

remainder = x % y
print(remainder) 

[ 12  11  34 105]
[ 8  5 26 95]
[ 20  24 120 500]
[ 5.          2.66666667  7.5        20.        ]
[0 2 2 0]


In [43]:
# mathematical function 

# trigonometry 

# sin , cos , tan takes values in radian 

sin_val = np.sin(x)
print(sin_val) 

cos_val = np.cos(x)
print(cos_val) 

deg_con = np.rad2deg(x)
print(deg_con)

# deg2rad 

[-0.54402111  0.98935825 -0.98803162 -0.50636564]
[-0.83907153 -0.14550003  0.15425145  0.86231887]
[ 572.95779513  458.3662361  1718.87338539 5729.57795131]


In [44]:
#log 

x = np.array([ 10 , 8 , 16 , 100 ])
base_10_log_val = np.log10(x)
print(base_10_log_val)


two_diye_bhag = np.log2(x) 
print(two_diye_bhag)

sqrt= np.sqrt(x)
print(sqrt)

[1.         0.90308999 1.20411998 2.        ]
[3.32192809 3.         4.         6.64385619]
[ 3.16227766  2.82842712  4.         10.        ]


In [45]:
# different 
s = np.sum(x)
print(s)

#prefix sum 
cumul =np.cumulative_sum(x)
print(cumul)

134


AttributeError: module 'numpy' has no attribute 'cumulative_sum'

In [46]:
#broadcasting 

x = np.array([ 10 , 8 , 16 , 100 ])

result = x + 2 

#rulings = columns er size and vector er size same hote hobe 

matrix = np.array([[10,20,30],
                [30,40,50]
               ])


result = matrix + 2 

vector = np.array([1,2,3,4]) 

result = matrix +vector
print(result)

ValueError: operands could not be broadcast together with shapes (2,3) (4,) 

## Logical Function

In [47]:
# comparison - >,< , >= ,<= , == , !=

x = np.array([ 10 , 8 , 16 , 100 ])
y = np.array([ 2 , 3 ,16  ,5 ]) 

greater_than = x>y 

print(greater_than)

equal = x==y 

print(equal) 

# all () -> shob true kina 
# any() -> jekono ekta true ase kina 

print(np.all(greater_than)) 

print(np.any(equal))

[ True  True False  True]
[False False  True False]
False
True


## Sorting

In [48]:
#inplace 
x = np.array([ 10 , 8 , 16 , 100 ])

z = x.copy()

print(z) 

z.sort()

print(z)


[ 10   8  16 100]
[  8  10  16 100]


In [49]:
# copy sorting
print(x)
sort_arr = np.sort(x) 

print(sort_arr)

print(x)

[ 10   8  16 100]
[  8  10  16 100]
[ 10   8  16 100]


In [50]:
# 2d array sorting 
mat = np.array([[10,3,5],[8,4,9]])

# horizon axis = 1 

hor_sort = np.sort(mat,axis=1)
print(hor_sort)

vert_sort = np.sort(mat,axis=0)
print(vert_sort)

[[ 3  5 10]
 [ 4  8  9]]
[[ 8  3  5]
 [10  4  9]]


## Searching

In [51]:
print(x)

[ 10   8  16 100]


In [52]:
# np.where( condition , x , y ) if true x , otherwise replace with y 

index = np.where(x==8) # returns index
print(index)

arr = np.where(x>8,x,0) # returns array 
print(arr)

(array([1]),)
[ 10   0  16 100]


In [53]:
print(mat)

[[10  3  5]
 [ 8  4  9]]


In [54]:
index = np.where(mat>8) # returns index
print(index)

arr = np.where(mat>8,mat,0) # returns array 
print(arr)

(array([0, 1]), array([0, 2]))
[[10  0  0]
 [ 0  0  9]]


In [55]:
x = np.array([ 10,100 , 8 , 16 , 100 ])

maximum_value_indx = np.argmax(x) 
minimum_value_indx = np.argmin(x)

print(maximum_value_indx)
print(minimum_value_indx)

1
2


## counting in ndarray

In [56]:
a = np.random.randint(1 ,100 , size =(100,))
print(a)

[10 39 32 53 39 37 54 39 69 91  1 44 26 52 61 40 22 84 74 44 96 50 98 26
 11 83 25 84 91 71 60 10 54 17 93 63 60 42 58 42 94 65 34 65  8 77 99  7
 96 66 54 74 18 68 20 48  8 78  3 70 43 18 57 65 73 59 51 27 79  5 46 82
 86 43 53 50 61 30 87 20 92  8  9 38 91 28 59 33 17  3 10 52 98 83 10 64
  9  1  9 11]


In [57]:
value_great_than_60 = np.count_nonzero(a==97)
print(value_great_than_60)

0


In [58]:
unique_value,count = np.unique(a,return_counts=True)

print(unique_value) 
print(count)

[ 1  3  5  7  8  9 10 11 17 18 20 22 25 26 27 28 30 32 33 34 37 38 39 40
 42 43 44 46 48 50 51 52 53 54 57 58 59 60 61 63 64 65 66 68 69 70 71 73
 74 77 78 79 82 83 84 86 87 91 92 93 94 96 98 99]
[2 2 1 1 3 3 4 2 2 2 2 1 1 2 1 1 1 1 1 1 1 1 3 1 2 2 2 1 1 2 1 2 2 3 1 1 2
 2 2 1 1 3 1 1 1 1 1 1 2 1 1 1 1 2 2 1 1 3 1 1 1 2 2 1]


## statistical function

In [59]:
#data load 

data = np.genfromtxt('student_scores.csv' ,delimiter=',',skip_header=1)

print(data) 

FileNotFoundError: student_scores.csv not found.

In [60]:
# statistics  
math_marks = data[::,:1]

print(math_marks.T)

max_math_marks = np.max(math_marks)
print(max_math_marks)

min_math_marks = np.min(math_marks)
print(min_math_marks)

average_math_marks = np.mean(math_marks)
print(average_math_marks)

median_math_marks = np.median(math_marks)
print(median_math_marks) 

# standard deviation

std_math_marks = np.std(math_marks)
print(std_math_marks)

NameError: name 'data' is not defined

In [61]:
study_hours = np.array([2, 4, 5, 7, 8])
exam_scores = np.array([65, 75, 78, 88, 92])

data = np.array([study_hours, exam_scores])

correlation = np.corrcoef(data)

print("Correlation Matrix:\n", correlation)

Correlation Matrix:
 [[1.         0.99859154]
 [0.99859154 1.        ]]


## linear algebra

In [62]:

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

# a er column and b er row same length hote hobe 
dot_product = np.dot(A,B)
print(dot_product)


# trace 
print(np.trace(B))


# 

[[ 58  64]
 [139 154]]
17


In [63]:

sq_mat = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]
         ])

det_of_sq = np.linalg.det(sq_mat)

rank_sq = np.linalg.matrix_rank(sq_mat)

print(det_of_sq)

print(rank_sq)

6.66133814775094e-16
2


In [64]:
A = np.array([[1, 2], [3, 4]]) 
B = np.array([[5, 6], [7, 8]])

print(np.dot(A,B))

[[19 22]
 [43 50]]


## Quiz

In [1]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)
print(b.shape)


(2, 3)


In [2]:
import numpy as np
np.sin(np.pi / 2)


1.0

In [5]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)


[5 7 9]


In [6]:
import numpy as np
a = np.array([3, 1, 2])
print(np.sort(a))


[1 2 3]


In [7]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A, B))


[[19 22]
 [43 50]]
