## Module covered topic
- Numpy - Nd Array Object.

- Numpy - Data Types.

- Numpy - Array Attributes.

- Numpy - Array Creation Routines.

- Numpy - Array From Existing.

- Data Array From Numerical Ranges.

- Numpy - Indexing & Slicing.

- Numpy - Advanced Indexing.

- Numpy - Broadcasting.

- Numpy - Iterating Over Array

- Numpy - Array Manipulation.

- Numpy - Conditional operations with all and any

- Numpy - String Functions.

- Numpy - Mathematical Functions.

- Numpy - Arithmetic Operations.

- Numpy - Statistical Functions.

- Sort, Search & Counting Functions.

- Numpy - Linear Algebra

In [2]:
import numpy as np 

a=np.array([
    [1,2,3],
    [4,5,6]
])

b=np.array([
    [7,8],
    [9,10],
    [11,12]
])

d=np.dot(a,b) # dot=dot gun
print(d)

[[ 58  64]
 [139 154]]


In [ ]:
d1=np.linalg.inv(d) # inv= inverce, linalg= linear algebra
print (d1)

[[ 4.27777778 -1.77777778]
 [-3.86111111  1.61111111]]


In [5]:
d2=np.linalg.matrix_transpose(d1)
print(d2)

[[ 4.27777778 -3.86111111]
 [-1.77777778  1.61111111]]


## Numpy Questions

### Array Creation and Manipulation
- 1.Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

- 2.Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [12]:
# 1
import numpy as np 

arr =np.random.randint(1,21,size=(5,5))
print(arr)

[[ 9 17  5  1 12]
 [13  1  4  4 11]
 [20 15  8 19 14]
 [ 1  7  1  2 10]
 [14 15 18 17 11]]


In [ ]:
arr[:, 2] # 2 number index er column

array([ 5,  4,  8,  1, 18])

In [ ]:
arr[2,:] # 2 num index er row

array([20, 15,  8, 19, 14])

In [ ]:
arr[:, 2]=1 # 2 number index er column =1
print(arr)

[[ 9 17  1  1 12]
 [13  1  1  4 11]
 [20 15  1 19 14]
 [ 1  7  1  2 10]
 [14 15  1 17 11]]


In [17]:
arr[2,:]=1
print(arr)

[[ 9 17  1  1 12]
 [13  1  1  4 11]
 [ 1  1  1  1  1]
 [ 1  7  1  2 10]
 [14 15  1 17 11]]


In [18]:
# 2
arr =np.random.randint(1,17,size=(4,4))
arr

array([[15, 14,  2, 16],
       [15,  1,  2, 16],
       [11,  1,  9,  6],
       [ 8,  7,  2,  4]])

In [19]:
np.fill_diagonal(arr,0)
print(arr)

[[ 0 14  2 16]
 [15  0  2 16]
 [11  1  0  6]
 [ 8  7  2  0]]


## Array Indexing and Slicing
- 1.Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

- 2.Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [20]:
#1
arr=np.random.randint(1,36,size=(6,6))
print(arr)

[[29 25 25 12  3  1]
 [ 2 29  1  9  3 28]
 [11 20 23 10 31  1]
 [21 24 19 25  7  3]
 [21 25  8 15 30 20]
 [30  9 20 19 25 22]]


In [23]:
arr2 = arr[2:5,1:4]
arr2

array([[20, 23, 10],
       [24, 19, 25],
       [25,  8, 15]])

In [24]:
arr2 = arr[2:5,1:4]
print(arr[2:5,1:4])

[[20 23 10]
 [24 19 25]
 [25  8 15]]


In [25]:
# 2
arr=np.random.randint(1,36,size=(5,5))
print(arr)

[[32  2 16 32 29]
 [25 21 30  5  9]
 [18 15  3  7 23]
 [13  9 20 21  9]
 [32 18 31 33 18]]


In [30]:
print(arr[0,:])
print(arr[-1,:])
print(arr[1:4,0])
print(arr[1:4, -1])

arr3=np.concatenate((arr[0,:],arr[-1,:],arr[1:4,0],arr[1:4,-1]))
print(arr3)

[32  2 16 32 29]
[32 18 31 33 18]
[25 18 13]
[ 9 23  9]
[32  2 16 32 29 32 18 31 33 18 25 18 13  9 23  9]


## Array Operations
- 1.Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

- 2.Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [32]:
#1
arr1=np.random.randint(1,36,size=(3,4))
arr2=np.random.randint(1,36,size=(3,4))
print(arr1)
print('\n')
print(arr2)

[[29 21 35 11]
 [17 13  1 33]
 [23 35  7  9]]


[[20 21 26  4]
 [13 15  8  5]
 [20 20 10 28]]


In [33]:
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[[49 42 61 15]
 [30 28  9 38]
 [43 55 17 37]]
[[  9   0   9   7]
 [  4  -2  -7  28]
 [  3  15  -3 -19]]
[[580 441 910  44]
 [221 195   8 165]
 [460 700  70 252]]
[[1.45       1.         1.34615385 2.75      ]
 [1.30769231 0.86666667 0.125      6.6       ]
 [1.15       1.75       0.7        0.32142857]]


In [34]:
# create a Numpy array of shape (4,4) with values from 1 to 16. Compute the row-wise and column wise sum.

#2

arr = np.random.randint(1,5,size=(5,5))
print(arr)

[[1 2 3 3 4]
 [1 3 3 4 2]
 [3 3 2 3 4]
 [4 3 2 1 4]
 [1 1 4 2 4]]


In [36]:
row_sum=np.sum(arr,axis=1)
print("Row sum",row_sum)
col_sum = np.sum(arr, axis=0)
print("Col sum ", col_sum)

Row sum [13 13 15 14 12]
Col sum  [10 12 14 13 18]


## Statistical Operations
- 1.Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [37]:
arr = np.random.randint(1, 25, size=(4, 4))
print(arr)
print("Mean = ", np.mean(arr))
print("Meadian = ", np.median(arr))
print("Standard Deviatio = ", np.std(arr))
print("Variance = ", np.var(arr))
print(dir(np))

[[17 13 12  2]
 [ 4 11 10 16]
 [16 18 15 11]
 [17  9  3 23]]
Mean =  12.3125
Meadian =  12.5
Standard Deviatio =  5.631593358011568
Variance =  31.71484375
['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__array_namespace_info__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_array_api_info', '_core', '_distributor_init', '_expired_attrs_2_0', '_globals', '_int_extended_msg', '_mat', '_msg', '_pyinstaller_hooks_dir', '_pytesttester', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arcta

## Broadcasting
- 1.Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

- 2.Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [38]:
# 1
arr = np.random.randint(1, 25, size=(3, 3))
arr1 = np.random.randint(1, 25, size=(3,))

print(arr)
print(arr1)
print(arr+arr1)

[[ 7  7 11]
 [ 5  8  7]
 [ 8 20 13]]
[11 17 12]
[[18 24 23]
 [16 25 19]
 [19 37 25]]


In [39]:
# print(arr1[:, np.newaxis])
# print(arr1[np.newaxis, :])
# print(arr1[:,np.newaxis])
print(arr1)  # 3
arr1.shape
arr2 = arr1.reshape(3, 1) # row =3, col = 1

print(arr - arr2)

[11 17 12]
[[ -4  -4   0]
 [-12  -9 -10]
 [ -4   8   1]]


## Linear Algebra
- 1.Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [40]:
# 1
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])
print(np.dot(A, B))

[[ 58  64]
 [139 154]]


## Advanced Array Manipulation
- 1.Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
- 2.Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [41]:
# 1
arr = np.random.randint(1, 10, size=(3, 3))
print(arr)

print(arr.reshape(1, 9))
print(arr.reshape(9, 1)) # row = 9 , col = 1

[[6 7 9]
 [7 7 4]
 [8 7 1]]
[[6 7 9 7 7 4 8 7 1]]
[[6]
 [7]
 [9]
 [7]
 [7]
 [4]
 [8]
 [7]
 [1]]


In [42]:
# 2
arr = np.random.randint(1, 10, size=(5, 5))
print(arr)
flatten_arr = arr.flatten()
print(flatten_arr)
arr2 = flatten_arr.reshape(6,5)
print(arr2)

[[1 4 4 7 2]
 [9 9 3 1 4]
 [9 1 1 4 8]
 [9 2 2 2 3]
 [4 4 8 8 8]]
[1 4 4 7 2 9 9 3 1 4 9 1 1 4 8 9 2 2 2 3 4 4 8 8 8]


ValueError: cannot reshape array of size 25 into shape (6,5)

In [43]:
import numpy as np

def reshape_matrix(a: list[list[int|float]], new_shape: tuple[int, int]) -> list[list[int|float]]:
	#Write your code here and return a python list after reshaping by using numpy's tolist() method
  arr = np.array(a)
  if arr.size != new_shape[0] * new_shape[1]:
      return []
  arr = arr.reshape(new_shape[0],new_shape[1])
  return arr.tolist()

print(reshape_matrix([[1,2,3,4],[5,6,7,8]], (2, 4)))

[[1, 2, 3, 4], [5, 6, 7, 8]]


## Boolean Indexing
- 1.Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [44]:
arr = np.random.randint(1, 100, size=(5, 5))
arr
print(arr)

[[78 88 48 48 78]
 [96 72 24 77 96]
 [77 34 15 98 82]
 [88 44 23 21 54]
 [98 83 22 22 86]]


In [45]:
print(arr[arr>10])
arr[arr>10] = 10
print(arr)

[78 88 48 48 78 96 72 24 77 96 77 34 15 98 82 88 44 23 21 54 98 83 22 22
 86]
[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


### Problem Solving

Easy https://www.deep-ml.com/problems/3




In [46]:
import numpy as np

def reshape_matrix(a: list[list[int|float]], new_shape: tuple[int, int]) -> list[list[int|float]]:
    #Write your code here and return a python list after reshaping by using numpy's tolist() method
    arr = np.array(a)
    if arr.size != new_shape[0] * new_shape[1]:
        return []
    arr = arr.reshape(new_shape[0],new_shape[1])
    return arr.tolist()

Easy https://www.deep-ml.com/problems/5

In [ ]:
import numpy as np
def scalar_multiply(matrix: list[list[int|float]], scalar: int|float) -> list[list[int|float]]:
    arr = np.array(matrix)
    arr = arr * scalar
  return arr.tolist()


IndentationError: unindent does not match any outer indentation level (<string>, line 5)

### Easy https://www.deep-ml.com/problems/35

In [56]:
import numpy as np

def make_diagonal(x):
	# Your code here
	return np.diag(x)

Easy https://www.deep-ml.com/problems/83

In [57]:
import numpy as np

def calculate_dot_product(vec1, vec2) -> float:
	"""
	Calculate the dot product of two vectors.
	Args:
		vec1 (numpy.ndarray): 1D array representing the first vector.
		vec2 (numpy.ndarray): 1D array representing the second vector.
	"""
	# Your code here
	return np.dot(vec1, vec2)

Easy https://www.deep-ml.com/problems/121