## Module covered topic
- Numpy - Nd Array Object.

- Numpy - Data Types.

- Numpy - Array Attributes.

- Numpy - Array Creation Routines.

- Numpy - Array From Existing.

- Data Array From Numerical Ranges.

- Numpy - Indexing & Slicing.

- Numpy - Advanced Indexing.

- Numpy - Broadcasting.

- Numpy - Iterating Over Array

- Numpy - Array Manipulation.

- Numpy - Conditional operations with all and any

- Numpy - String Functions.

- Numpy - Mathematical Functions.

- Numpy - Arithmetic Operations.

- Numpy - Statistical Functions.

- Sort, Search & Counting Functions.

- Numpy - Linear Algebra

In [ ]:
# dot gun
import numpy as np 

a=np.array([
    [1,2,3],
    [4,5,6]
])

b=np.array([
    [7,8],
    [9,10],
    [11,12]
])

d=np.dot(a,b) # dot=dot gun
print(d)

[[ 58  64]
 [139 154]]


In [ ]:
d1=np.linalg.inv(d) # inv= inverce, linalg= linear algebra
print (d1)

[[ 4.27777778 -1.77777778]
 [-3.86111111  1.61111111]]


In [5]:
d2=np.linalg.matrix_transpose(d1)
print(d2)

[[ 4.27777778 -3.86111111]
 [-1.77777778  1.61111111]]


## Numpy Questions

### Array Creation and Manipulation
- 1.Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

- 2.Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [4]:
# 1
import numpy as np 

arr =np.random.randint(1,21,size=(5,5)) # 21 dile 20 pojonto hobe. random value hobe 
# (5,5) --> row 5 ta column 5 ta.
print(arr)

[[ 8  7  9 16  7]
 [ 4 16  9  1 20]
 [ 3 15  9  7  6]
 [10 11 11 16 15]
 [ 2  5  5  1 11]]


In [5]:
print(arr[0][0])

8


In [6]:
print(arr[1]) #  1 index er row

[ 4 16  9  1 20]


In [7]:
arr[:, 2] # 2 number index er column

array([ 9,  9,  9, 11,  5])

In [8]:
arr[2,:] # 2 num index er row

array([ 3, 15,  9,  7,  6])

In [9]:
arr[:, 2]=1 # 2 number index er column =1
print(arr)

[[ 8  7  1 16  7]
 [ 4 16  1  1 20]
 [ 3 15  1  7  6]
 [10 11  1 16 15]
 [ 2  5  1  1 11]]


In [10]:
arr[2,:]=1
print(arr)

[[ 8  7  1 16  7]
 [ 4 16  1  1 20]
 [ 1  1  1  1  1]
 [10 11  1 16 15]
 [ 2  5  1  1 11]]


In [11]:
# 2
arr =np.random.randint(1,17,size=(4,4))
arr

array([[ 3,  5, 10, 12],
       [ 5,  2,  7,  1],
       [12,  8,  2,  8],
       [14,  7,  4,  7]])

In [ ]:
np.fill_diagonal(arr,0) # diagonali--> 0 hobe
print(arr)

[[ 0  5 10 12]
 [ 5  0  7  1]
 [12  8  0  8]
 [14  7  4  0]]


## Array Indexing and Slicing
- 1.Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

- 2.Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [14]:
#1
arr=np.random.randint(1,36,size=(6,6))
print(arr)

[[ 4 27  1 34 29 11]
 [29 27 35 24  4  9]
 [ 8 20 31  3  7  9]
 [10 21 12 23 35 19]
 [32 20 31 30  3 17]
 [14  4 16 22 15 14]]


In [15]:
arr2 = arr[2:5,1:4] # arr[row,column]
arr2

array([[20, 31,  3],
       [21, 12, 23],
       [20, 31, 30]])

In [16]:
arr2 = arr[2:5,1:4]
print(arr[2:5,1:4])

[[20 31  3]
 [21 12 23]
 [20 31 30]]


In [ ]:
# 2
arr=np.random.randint(1,36,size=(5,5))
print(arr)

# 1st row and column == 0

[[ 2  4 11 33 19]
 [16 31  8  2 14]
 [21 26 27 29 32]
 [23  5 31 28 11]
 [28 19 33  1 35]]


In [ ]:
print(arr[0,:])
print(arr[4,:]) 
print(arr[-1,:]) # arr[4,:]  same
print(arr[1:4,0]) # 1-4 num row . and 0 num column
print(arr[1:4, -1]) # 1-4 num row . and shes num column

arr3=np.concatenate((arr[0,:],arr[-1,:],arr[1:4,0],arr[1:4,-1]))
print(arr3) # sob gulo array er modhe ashe porbe. 

[ 2  4 11 33 19]
[28 19 33  1 35]
[28 19 33  1 35]
[16 21 23]
[14 32 11]
[ 2  4 11 33 19 28 19 33  1 35 16 21 23 14 32 11]


## Array Operations
- 1.Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

- 2.Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [32]:
#1
arr1=np.random.randint(1,36,size=(3,4))
arr2=np.random.randint(1,36,size=(3,4))
print(arr1)
print('\n')
print(arr2)

[[29 21 35 11]
 [17 13  1 33]
 [23 35  7  9]]


[[20 21 26  4]
 [13 15  8  5]
 [20 20 10 28]]


In [33]:
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[[49 42 61 15]
 [30 28  9 38]
 [43 55 17 37]]
[[  9   0   9   7]
 [  4  -2  -7  28]
 [  3  15  -3 -19]]
[[580 441 910  44]
 [221 195   8 165]
 [460 700  70 252]]
[[1.45       1.         1.34615385 2.75      ]
 [1.30769231 0.86666667 0.125      6.6       ]
 [1.15       1.75       0.7        0.32142857]]


In [34]:
# create a Numpy array of shape (4,4) with values from 1 to 16. Compute the row-wise and column wise sum.

#2

arr = np.random.randint(1,5,size=(5,5))
print(arr)

[[1 2 3 3 4]
 [1 3 3 4 2]
 [3 3 2 3 4]
 [4 3 2 1 4]
 [1 1 4 2 4]]


In [ ]:
row_sum=np.sum(arr,axis=1) # axis=1 mane row bujai 
# row sum korbo. firstly 0 index sum kore 1st a 13 bosayce
print("Row sum",row_sum)
col_sum = np.sum(arr, axis=0) # axis=0 --> column
print("Col sum ", col_sum)

Row sum [13 13 15 14 12]
Col sum  [10 12 14 13 18]


## Statistical Operations
- 1.Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [24]:
arr = np.random.randint(1, 25, size=(4, 4))
print(arr)
print("Mean = ", np.mean(arr))
print("Meadian = ", np.median(arr))
print("Standard Deviatio = ", np.std(arr))
print("Variance = ", np.var(arr))
print(dir(np))

[[20  7  2  7]
 [19  8 11 12]
 [20 12 22 19]
 [22  9 21  9]]
Mean =  13.75
Meadian =  12.0
Standard Deviatio =  6.339361166552983
Variance =  40.1875
['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__array_namespace_info__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_array_api_info', '_core', '_distributor_init', '_expired_attrs_2_0', '_globals', '_int_extended_msg', '_mat', '_msg', '_pyinstaller_hooks_dir', '_pytesttester', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', '

## Broadcasting
- 1.Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

- 2.Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [25]:
# 1
arr = np.random.randint(1, 25, size=(3, 3))
arr1 = np.random.randint(1, 25, size=(3,))

print(arr)
print(arr1)
print(arr+arr1)

[[ 8 22 13]
 [11 10 21]
 [22  7 22]]
[24 17  2]
[[32 39 15]
 [35 27 23]
 [46 24 24]]


In [ ]:
print(arr1) # same
print(arr1[:, np.newaxis]) # column
print(arr1[np.newaxis,:]) # same row wise --> ( : er age hole row  pore hole column)

[24 17  2]
[[24]
 [17]
 [ 2]]
[[24 17  2]]


In [31]:
# print(arr1[:, np.newaxis])
# print(arr1[np.newaxis, :])
# print(arr1[:,np.newaxis])
print(arr1)  # 3
arr1.shape


[24 17  2]


(3,)

In [32]:
arr2 = arr1.reshape(3, 1) # row =3, col = 1
print(arr2)

print(arr - arr2)

[[24]
 [17]
 [ 2]]
[[-16  -2 -11]
 [ -6  -7   4]
 [ 20   5  20]]


## Linear Algebra
- 1.Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [ ]:
 # 1
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])
print(np.dot(A, B))

[[ 58  64]
 [139 154]]


## Advanced Array Manipulation
- 1.Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
- 2.Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [33]:
# 1
arr = np.random.randint(1, 10, size=(3, 3))
print(arr)

print(arr.reshape(1, 9))
print(arr.reshape(9, 1)) # row = 9 , col = 1

[[1 6 6]
 [7 3 4]
 [6 1 3]]
[[1 6 6 7 3 4 6 1 3]]
[[1]
 [6]
 [6]
 [7]
 [3]
 [4]
 [6]
 [1]
 [3]]


In [37]:
# 2
arr = np.random.randint(1, 10, size=(5, 5))
print(arr)
print('\n')
flatten_arr = arr.flatten()
print(flatten_arr)
print('\n')
arr2 = flatten_arr.reshape(5,5)
print(arr2)

[[4 2 5 8 3]
 [7 4 6 7 4]
 [2 5 5 2 7]
 [4 8 9 8 7]
 [4 5 5 6 2]]


[4 2 5 8 3 7 4 6 7 4 2 5 5 2 7 4 8 9 8 7 4 5 5 6 2]


[[4 2 5 8 3]
 [7 4 6 7 4]
 [2 5 5 2 7]
 [4 8 9 8 7]
 [4 5 5 6 2]]


In [43]:
import numpy as np

def reshape_matrix(a: list[list[int|float]], new_shape: tuple[int, int]) -> list[list[int|float]]:
	#Write your code here and return a python list after reshaping by using numpy's tolist() method
  arr = np.array(a)
  if arr.size != new_shape[0] * new_shape[1]:
      return []
  arr = arr.reshape(new_shape[0],new_shape[1])
  return arr.tolist()

print(reshape_matrix([[1,2,3,4],[5,6,7,8]], (2, 4)))

[[1, 2, 3, 4], [5, 6, 7, 8]]


## Boolean Indexing
- 1.Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [44]:
arr = np.random.randint(1, 100, size=(5, 5))
arr
print(arr)

[[78 88 48 48 78]
 [96 72 24 77 96]
 [77 34 15 98 82]
 [88 44 23 21 54]
 [98 83 22 22 86]]


In [45]:
print(arr[arr>10])
arr[arr>10] = 10
print(arr)

[78 88 48 48 78 96 72 24 77 96 77 34 15 98 82 88 44 23 21 54 98 83 22 22
 86]
[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


### Problem Solving

Easy https://www.deep-ml.com/problems/3




In [46]:
import numpy as np

def reshape_matrix(a: list[list[int|float]], new_shape: tuple[int, int]) -> list[list[int|float]]:
    #Write your code here and return a python list after reshaping by using numpy's tolist() method
    arr = np.array(a)
    if arr.size != new_shape[0] * new_shape[1]:
        return []
    arr = arr.reshape(new_shape[0],new_shape[1])
    return arr.tolist()

Easy https://www.deep-ml.com/problems/5

In [ ]:
import numpy as np
def scalar_multiply(matrix: list[list[int|float]], scalar: int|float) -> list[list[int|float]]:
    arr = np.array(matrix)
    arr = arr * scalar
  return arr.tolist()


IndentationError: unindent does not match any outer indentation level (<string>, line 5)

### Easy https://www.deep-ml.com/problems/35

In [56]:
import numpy as np

def make_diagonal(x):
	# Your code here
	return np.diag(x)

Easy https://www.deep-ml.com/problems/83

In [57]:
import numpy as np

def calculate_dot_product(vec1, vec2) -> float:
	"""
	Calculate the dot product of two vectors.
	Args:
		vec1 (numpy.ndarray): 1D array representing the first vector.
		vec2 (numpy.ndarray): 1D array representing the second vector.
	"""
	# Your code here
	return np.dot(vec1, vec2)

Easy https://www.deep-ml.com/problems/121