# Import Libraries

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


# Train test split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [7]:
df['diagnosis'].unique()

array(['M', 'B'], dtype=object)

In [8]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [10]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [11]:
len(df.columns)

31

In [12]:
len(X_train) + len(X_test)

569

In [13]:
X_train

array([[-0.18829695,  0.53903187, -0.23370487, ..., -0.05100569,
         0.12064881, -0.71035321],
       [ 1.68994254,  0.09412088,  1.58440096, ...,  0.42086763,
         0.21659196, -1.37500122],
       [ 1.07224771,  0.17522444,  0.90038519, ...,  0.05904783,
         3.09016793, -1.27746837],
       ...,
       [ 1.94987747,  1.69533699,  2.05390291, ...,  2.64907454,
         1.85706253,  2.40960208],
       [-0.18550195, -0.22102441, -0.21670566, ..., -0.53478891,
        -0.37636816, -1.00788319],
       [ 0.24772293, -0.86753569,  0.22244056, ...,  0.35151883,
         0.05773527, -0.04406139]])

In [14]:
y_train

array([1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,

In [15]:
X_train

array([[-0.18829695,  0.53903187, -0.23370487, ..., -0.05100569,
         0.12064881, -0.71035321],
       [ 1.68994254,  0.09412088,  1.58440096, ...,  0.42086763,
         0.21659196, -1.37500122],
       [ 1.07224771,  0.17522444,  0.90038519, ...,  0.05904783,
         3.09016793, -1.27746837],
       ...,
       [ 1.94987747,  1.69533699,  2.05390291, ...,  2.64907454,
         1.85706253,  2.40960208],
       [-0.18550195, -0.22102441, -0.21670566, ..., -0.53478891,
        -0.37636816, -1.00788319],
       [ 0.24772293, -0.86753569,  0.22244056, ...,  0.35151883,
         0.05773527, -0.04406139]])

In [16]:
type(y_train)

numpy.ndarray

In [17]:
type(y_test)

numpy.ndarray

# Numpy Array to tensors

In [18]:
#numpy to tensor
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)

#change dtype
X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)

#numpy to tensor
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

y_train_tensor = torch.tensor(y_train_tensor,dtype= torch.float32)
y_test_tensor = torch.tensor(y_test_tensor, dtype=torch.float32)

# y_test_tensor = torch.from_numpy(y_test)

/tmp/ipykernel_224/3826779354.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32)
/tmp/ipykernel_224/3826779354.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)
/tmp/ipykernel_224/3826779354.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_train_tensor = torch.tensor(y_train_tensor,dtype= torch.float32)
/tmp/ipykernel_224/3826779354.py:14: UserWarning: To copy construct from a tensor, it is recommend

In [19]:
type(X_train_tensor)

torch.Tensor

# Dataset and Dataloader

In [20]:
from torch.utils.data import Dataset,DataLoader

In [21]:
class CustomDataset(Dataset):
  def __init__( self,features,labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self,index):
    return self.features[index], self.labels[index]

In [22]:
train_dataset = CustomDataset(X_train_tensor,y_train_tensor)
test_dataset = CustomDataset(X_test_tensor,y_test_tensor)

In [23]:
len(train_dataset)

455

In [24]:
train_dataset[2]

(tensor([ 1.0722,  0.1752,  0.9004,  0.9121, -0.9074, -0.7260, -0.2123,  0.1662,
          1.0887, -1.8231,  0.5018, -0.0118,  0.2234,  0.2776, -1.0080, -0.9557,
         -0.3032, -0.3084,  3.3404, -0.7257,  0.8906,  0.3689,  0.6485,  0.6679,
         -1.1088, -0.8558, -0.2327,  0.0590,  3.0902, -1.2775]),
 tensor(1.))

#loader

In [25]:
train_loader = DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader = DataLoader(test_dataset,batch_size=32,shuffle=True)

# Defining the Model

In [26]:
X_train.shape[1]

30

In [27]:
import torch.nn as nn

In [28]:
class MySimpleNN(nn.Module):

  def __init__(self,num_features):
    super().__init__()

    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out


In [29]:
torch.rand(30,1)

tensor([[0.0911],
        [0.0425],
        [0.3246],
        [0.8447],
        [0.1146],
        [0.3614],
        [0.2260],
        [0.8770],
        [0.5478],
        [0.9581],
        [0.7525],
        [0.6630],
        [0.4912],
        [0.2850],
        [0.7283],
        [0.9420],
        [0.8461],
        [0.2413],
        [0.5234],
        [0.5141],
        [0.2843],
        [0.9083],
        [0.5011],
        [0.2136],
        [0.8168],
        [0.7234],
        [0.6915],
        [0.6892],
        [0.5457],
        [0.2601]])

# Parameters

In [30]:
X_train_tensor.shape[1]

30

In [31]:
learning_rate = 0.1
epochs = 25

In [32]:
loss_function = nn.BCELoss()

In [33]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [34]:
model = MySimpleNN(X_train_tensor.shape[1])


In [35]:
model.parameters()

<generator object Module.parameters at 0x7c9f87fe6340>

In [36]:
X_test_tensor.dtype

torch.float32

In [37]:
model.linear.weight.dtype

torch.float32

In [38]:
y_train_tensor.dtype

torch.float32

In [39]:
model.parameters()

<generator object Module.parameters at 0x7c9f87fe6420>

# Training Pipeline

In [40]:
#create model

model = MySimpleNN(X_train_tensor.shape[1])

#optimizer
optimizer = torch.optim.SGD( model.parameters(), lr = learning_rate )

#define loop

for epoch in range(epochs):

  for batch_feature,batch_labels in train_loader:
    #forward pass
    y_pred = model(batch_feature)
    #Loss calculate
    loss = loss_function(y_pred,batch_labels.reshape(-1,1))

    #zero gradient
    optimizer.zero_grad()
    #backward pass
    loss.backward()

    #parameter update
    optimizer.step()



  #print loss in each epoch

  print(f" {epoch+1} , Loss = {loss.item()} ")

 1 , Loss = 0.1859939843416214 
 2 , Loss = 0.15529651939868927 
 3 , Loss = 0.20516140758991241 
 4 , Loss = 0.09281878173351288 
 5 , Loss = 0.02875235304236412 
 6 , Loss = 0.06507090479135513 
 7 , Loss = 0.02887875773012638 
 8 , Loss = 0.04400952532887459 
 9 , Loss = 0.1693538874387741 
 10 , Loss = 0.07063940912485123 
 11 , Loss = 0.007057373411953449 
 12 , Loss = 0.011542108841240406 
 13 , Loss = 0.044675957411527634 
 14 , Loss = 0.006882091518491507 
 15 , Loss = 0.012221367098391056 
 16 , Loss = 0.026774730533361435 
 17 , Loss = 0.005117639899253845 
 18 , Loss = 0.0017901199171319604 
 19 , Loss = 0.03545026108622551 
 20 , Loss = 0.06128436699509621 
 21 , Loss = 0.11416144669055939 
 22 , Loss = 0.04239241033792496 
 23 , Loss = 0.02956182137131691 
 24 , Loss = 0.05961504206061363 
 25 , Loss = 0.050409089773893356 


# Training pipeline version 2

In [ ]:
#create model

model = MySimpleNN(X_train_tensor.shape[1])

#optimizer
optimizer = torch.optim.SGD( model.parameters(), lr = learning_rate )

#define loop
batch_size = 32
epoch = 25
n_sample = len(X_train_tensor)

for epoch in range(epochs):

  for start_indx in range(0,n_sample,batch_size):
    end_indx = start_indx + batch_size

    print(f" Start index {start_indx}, end indx {end_indx}\n")

    X_batch = X_train_tensor[start_indx:end_indx]
    y_batch = y_train_tensor[start_indx:end_indx]

    #forward pass
    y_pred = model(X_batch)
    loss = loss_function(y_pred,y_batch.reshape(-1,1))


    #upate step

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()



  #print loss in each epoch

  # print(f" {epoch+1} , Loss = {loss.item()} ")

# Model Evaluation (old)

In [42]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred= (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f" Accuracy = {accuracy.item()}")

 Accuracy = 0.5495536923408508


# Better version

In [72]:
y_pred.shape

torch.Size([18, 1])

In [73]:
batch_labels.shape

torch.Size([18])

In [80]:
model.eval()  #evaluation mode
accuracy_list = []

with torch.no_grad():
  for batch_features, batch_labels in test_loader:
    y_pred = model(batch_features)
    y_pred = (y_pred > 0.5).float()

    batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()

    accuracy_list.append(batch_accuracy)


overall_accuracy = sum(accuracy_list) / len(accuracy_list)

print(overall_accuracy)




0.9765625


In [75]:
accuracy_list

[0.90625, 0.9375, 0.90625, 0.9444444179534912]

# Summary

In [46]:
X_train_tensor.shape

torch.Size([455, 30])

In [47]:
!pip install torchinfo

In [48]:
from torchinfo import summary

In [49]:
summary(model, input_size = (455,30))

Layer (type:depth-idx)                   Output Shape              Param #
MySimpleNN                               [455, 1]                  --
├─Linear: 1-1                            [455, 1]                  31
├─Sigmoid: 1-2                           [455, 1]                  --
Total params: 31
Trainable params: 31
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.01
Input size (MB): 0.05
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.06