## Module covered topic
- Numpy - Nd Array Object.

- Numpy - Data Types.

- Numpy - Array Attributes.

- Numpy - Array Creation Routines.

- Numpy - Array From Existing.

- Data Array From Numerical Ranges.

- Numpy - Indexing & Slicing.

- Numpy - Advanced Indexing.

- Numpy - Broadcasting.

- Numpy - Iterating Over Array

- Numpy - Array Manipulation.

- Numpy - Conditional operations with all and any

- Numpy - String Functions.

- Numpy - Mathematical Functions.

- Numpy - Arithmetic Operations.

- Numpy - Statistical Functions.

- Sort, Search & Counting Functions.

- Numpy - Linear Algebra

In [2]:
import numpy as np 

a=np.array([
    [1,2,3],
    [4,5,6]
])

b=np.array([
    [7,8],
    [9,10],
    [11,12]
])

d=np.dot(a,b) # dot=dot gun
print(d)

[[ 58  64]
 [139 154]]


In [ ]:
d1=np.linalg.inv(d) # inv= inverce, linalg= linear algebra
print (d1)

[[ 4.27777778 -1.77777778]
 [-3.86111111  1.61111111]]


In [5]:
d2=np.linalg.matrix_transpose(d1)
print(d2)

[[ 4.27777778 -3.86111111]
 [-1.77777778  1.61111111]]


## Numpy Questions

### Array Creation and Manipulation
- 1.Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

- 2.Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [12]:
# 1
import numpy as np 

arr =np.random.randint(1,21,size=(5,5))
print(arr)

[[ 9 17  5  1 12]
 [13  1  4  4 11]
 [20 15  8 19 14]
 [ 1  7  1  2 10]
 [14 15 18 17 11]]


In [ ]:
arr[:, 2] # 2 number index er column

array([ 5,  4,  8,  1, 18])

In [ ]:
arr[2,:] # 2 num index er row

array([20, 15,  8, 19, 14])

In [ ]:
arr[:, 2]=1 # 2 number index er column =1
print(arr)

[[ 9 17  1  1 12]
 [13  1  1  4 11]
 [20 15  1 19 14]
 [ 1  7  1  2 10]
 [14 15  1 17 11]]


In [17]:
arr[2,:]=1
print(arr)

[[ 9 17  1  1 12]
 [13  1  1  4 11]
 [ 1  1  1  1  1]
 [ 1  7  1  2 10]
 [14 15  1 17 11]]


In [18]:
# 2
arr =np.random.randint(1,17,size=(4,4))
arr

array([[15, 14,  2, 16],
       [15,  1,  2, 16],
       [11,  1,  9,  6],
       [ 8,  7,  2,  4]])

In [19]:
np.fill_diagonal(arr,0)
print(arr)

[[ 0 14  2 16]
 [15  0  2 16]
 [11  1  0  6]
 [ 8  7  2  0]]


## Array Indexing and Slicing
- 1.Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

- 2.Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [20]:
#1
arr=np.random.randint(1,36,size=(6,6))
print(arr)

[[29 25 25 12  3  1]
 [ 2 29  1  9  3 28]
 [11 20 23 10 31  1]
 [21 24 19 25  7  3]
 [21 25  8 15 30 20]
 [30  9 20 19 25 22]]


In [23]:
arr2 = arr[2:5,1:4]
arr2

array([[20, 23, 10],
       [24, 19, 25],
       [25,  8, 15]])

In [24]:
arr2 = arr[2:5,1:4]
print(arr[2:5,1:4])

[[20 23 10]
 [24 19 25]
 [25  8 15]]


In [25]:
# 2
arr=np.random.randint(1,36,size=(5,5))
print(arr)

[[32  2 16 32 29]
 [25 21 30  5  9]
 [18 15  3  7 23]
 [13  9 20 21  9]
 [32 18 31 33 18]]


In [30]:
print(arr[0,:])
print(arr[-1,:])
print(arr[1:4,0])
print(arr[1:4, -1])

arr3=np.concatenate((arr[0,:],arr[-1,:],arr[1:4,0],arr[1:4,-1]))
print(arr3)

[32  2 16 32 29]
[32 18 31 33 18]
[25 18 13]
[ 9 23  9]
[32  2 16 32 29 32 18 31 33 18 25 18 13  9 23  9]


## Array Operations
- 1.Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

- 2.Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [32]:
#1
arr1=np.random.randint(1,36,size=(3,4))
arr2=np.random.randint(1,36,size=(3,4))
print(arr1)
print('\n')
print(arr2)

[[29 21 35 11]
 [17 13  1 33]
 [23 35  7  9]]


[[20 21 26  4]
 [13 15  8  5]
 [20 20 10 28]]


In [33]:
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[[49 42 61 15]
 [30 28  9 38]
 [43 55 17 37]]
[[  9   0   9   7]
 [  4  -2  -7  28]
 [  3  15  -3 -19]]
[[580 441 910  44]
 [221 195   8 165]
 [460 700  70 252]]
[[1.45       1.         1.34615385 2.75      ]
 [1.30769231 0.86666667 0.125      6.6       ]
 [1.15       1.75       0.7        0.32142857]]


In [34]:
# create a Numpy array of shape (4,4) with values from 1 to 16. Compute the row-wise and column wise sum.

#2

arr = np.random.randint(1,5,size=(5,5))
print(arr)

[[1 2 3 3 4]
 [1 3 3 4 2]
 [3 3 2 3 4]
 [4 3 2 1 4]
 [1 1 4 2 4]]
