- Intro to Numpy
- ndarray and its attributes
- Ndarray Data Type
- Ndarray creating from Existing data
- Ndarray creating from scratch
- Ndarray generation with random values
- Ndarray creation from range
- Creating digonal and identity matrix
- Ndarray Idexing and Slicing
- Ndarray Indexing and Slicing
- Ndarray Copy Advanced Indexing and Iteration


In [2]:
arr=[1,2,3]
print(arr*5)

arr=[x*5 for x in arr]
print(arr)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[5, 10, 15]


In [3]:
import numpy as np

arr1 =np.array([1,2,3])
arr1=arr1*5
print(arr1)

[ 5 10 15]


## Ndarray

In [3]:
import numpy as np

# 1d array
arr1=np.array([1,2,3,4,5])
print(type(arr1))
print(arr1.ndim)


<class 'numpy.ndarray'>
1


In [ ]:
import numpy as np

#1d array
arr1=np.array([1,2,3,4,5,6])
print(type(arr1))
print(arr1.ndim)# number of dimension


#2d array
arr2=np.array([[1,2,3,6],# 1d
              [4,5,6,7] #2d
              ])
print(arr2.ndim)


#3d array 
arr3 = np.array([
    #1st floor
    [ [1,2,3], # row1
      [4,5,6]  ], #row2 

    #2nd floor

     [[1,2,3], # row1
      [4,5,6]  ], #row2  


    #3rd floor
      [[1,2,3], # row1
      [4,5,6]  ] #row2  
   
])

print(type(arr3))
print(arr3.ndim)

<class 'numpy.ndarray'>
1
2
<class 'numpy.ndarray'>
3


## Array attributes

In [ ]:
# dimension 
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim) 


#shape 
print(arr1.shape)
print(arr2.shape)
print(arr3.shape) 


#data type 
print(arr1.dtype)# data type
print(arr2.dtype)
print(arr3.dtype)


#size 
print(arr1.size)
print(arr2.size)
print(arr3.size)

1
2
3
(6,)
(2, 4)
(3, 2, 3)
int64
int64
int64
6
8
18


## ndarray data type

In [56]:
arr =np.array([1,2,3])
print(arr.dtype)

arr=np.array([1.5,2.5,3.2])
print(arr.dtype)


int64
float64


In [73]:
# upcasted to float 
arr = np.array([1,2,3.2]) # NumPy=np
print(arr.dtype) 

#upcasted to string
arr = np.array([1,2,3.2,'hello']) 
print(arr.dtype) 


arr = np.array([1,True,3.25,'hello',]) 
print(arr.dtype) 

float64
<U32
<U32


## selecting a data type for an array

In [66]:
arr = np.array([1,2,3],dtype=np.int8)# Int a convert korbe
print(arr.dtype)
print(arr)

arr = np.array([1,2,3.6],dtype=np.float128)# Int a convert korbe
print(arr.dtype)
print(arr)


arr = arr.astype(np.int32)  #type change korar method
print(arr.dtype)

arr=np.array([1,2,3])
print(arr.dtype)
arr=arr.astype(np.int16)
print(arr.dtype)


#error
arr = np.array([1,2,3.2,'hello'],dtype=np.float64) #float a convert korbe . but ekta string thaker karone float hobe na. tai error 

int8
[1 2 3]
float128
[1.  2.  3.6]
int32
int64
int16


ValueError: could not convert string to float: 'hello'

## ndarray creation from existing data

In [71]:
#list 
lst = [10,20,30,40,40.5]### N-dimensional array--> ndarray
arr=np.array(lst)
print(arr)
print(type(arr))
print(arr.dtype)


lst = [10,20,30,40,40.5] 
arr = np.array(lst, dtype=np.int32) 
print(arr) 
print(type(arr)) 
print(arr.dtype) 


mixed_lst = [10, True , 'Hello' ]
arr = np.array(mixed_lst) 
print(arr) 
print(type(arr)) 
print(arr.dtype) 


matrix = [ [1,2,3], # row1
           [4,5,6] #row2
                ]

arr = np.array(matrix) 

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim) 

[10.  20.  30.  40.  40.5]
<class 'numpy.ndarray'>
float64
[10 20 30 40 40]
<class 'numpy.ndarray'>
int32
['10' 'True' 'Hello']
<class 'numpy.ndarray'>
<U21
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64
(2, 3)
2


In [81]:
#tuple 

tpl = (10,20,30) 

arr=np.array(tpl)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

# dui vabe kora jay . same

tpl = (10,20,30) 

arr = np.array(tpl,dtype=np.int32)
print(arr.dtype) #same
arr = arr.astype(np.int16)
print(arr.dtype) # same.dui rokom vabe kora jay
print(arr) 
print(type(arr)) 
print(arr.shape) 
print(arr.ndim) 

[10 20 30]
<class 'numpy.ndarray'>
int64
(3,)
1
int32
int16
[10 20 30]
<class 'numpy.ndarray'>
(3,)
1


In [74]:
#set 

st = { 1, 2, 3 }

arr = np.array(list(st))
print(arr.dtype) 

arr = arr.astype(np.int16)
print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim) 

int64
[1 2 3]
<class 'numpy.ndarray'>
int16
(3,)
1


In [87]:
# dictionary 

dc={'a':10,'b':20,'c':30}
kes=dc.keys()
print(kes)
values=dc.values()
print(values)
items=dc.items()
print(items)

dict_keys(['a', 'b', 'c'])
dict_values([10, 20, 30])
dict_items([('a', 10), ('b', 20), ('c', 30)])


In [ ]:
#keys to ndarray
arr = np.array(list(kes))
print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)


['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
(3,)
1
3


In [96]:
#values to ndarray
arr = np.array(list(values))
print(arr) 

arr = arr.astype(np.int16)
print(type(arr)) 

print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)    
print(arr.size)

[10 20 30]
<class 'numpy.ndarray'>
int16
(3,)
1
3


In [ ]:
#items to ndarray
arr = np.array(list(items))
print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)# 6 ta value

[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
<U21
(3, 2)
2
6


## Creating ndarray from scratch

In [106]:
# np.zeros

arr=np.zeros((1,3))
print(arr) 

arr=np.zeros((1,3),dtype=np.int8)
print(arr) 

print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)


arr=np.zeros_like(arr3)
print(arr3)
print(arr) 
print(arr.shape)


[[0. 0. 0.]]
[[0 0 0]]
<class 'numpy.ndarray'>
int8
(1, 3)
2
3
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
(3, 2, 3)


In [99]:
# np.zeros
arr = np.zeros((2,3),dtype=np.int8)

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

arr = np.zeros_like(arr3) ## arr3 shape same 
print(arr)
print(arr.shape) 

[[0 0 0]
 [0 0 0]]
<class 'numpy.ndarray'>
int8
(2, 3)
2
6
[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
(3, 2, 3)


In [112]:
#np.ones

arr=np.zeros((1,3),dtype=np.int8)
print(arr) 

arr=np.ones((4,3),dtype=np.int8)
print(arr) 

arr = np.ones((3,4,3),dtype=np.int8)

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)


arr = np.ones_like(arr3) ## arr3 shape same 
print(arr)
print(arr.shape) 


[[0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]]
<class 'numpy.ndarray'>
int8
(3, 4, 3)
3
36
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(3, 2, 3)


In [113]:
#np.empty
arr = np.empty((4,3),dtype=np.int8)

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

arr = np.empty_like(arr3) ## arr3 shape same 
print(arr)
print(arr.shape) 

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
<class 'numpy.ndarray'>
int8
(4, 3)
2
12
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(3, 2, 3)


In [119]:
#np.full 

arr = np.full((1,3),np.inf)
print(arr) 

arr = np.full((1,3),True)
print(arr) 

arr = np.full((4,3),10)
print(arr) 

print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

arr = np.full_like(arr3,np.inf) 
print(arr)

arr = np.full_like(arr3,np.inf,dtype=np.float64) 
print(arr)
print(arr.shape)
print(arr.dtype)

[[inf inf inf]]
[[ True  True  True]]
[[10 10 10]
 [10 10 10]
 [10 10 10]
 [10 10 10]]
<class 'numpy.ndarray'>
int64
(4, 3)
2
12
[[[-9223372036854775808 -9223372036854775808 -9223372036854775808]
  [-9223372036854775808 -9223372036854775808 -9223372036854775808]]

 [[-9223372036854775808 -9223372036854775808 -9223372036854775808]
  [-9223372036854775808 -9223372036854775808 -9223372036854775808]]

 [[-9223372036854775808 -9223372036854775808 -9223372036854775808]
  [-9223372036854775808 -9223372036854775808 -9223372036854775808]]]
[[[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]]
(3, 2, 3)
float64


/usr/lib/python3/dist-packages/numpy/core/numeric.py:407: RuntimeWarning: invalid value encountered in cast
  multiarray.copyto(res, fill_value, casting='unsafe')


## array creation with random values

In [131]:
# np.random.rand(shape) 

arr = np.random.rand(2,3) # (0 -1) random value 0 theke 1 porjonto hobe

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[[0.66189385 0.41369293 0.0631402 ]
 [0.79666164 0.70395358 0.04438919]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6


In [138]:
# np.random.randint(start,end, shape) 

arr = np.random.randint(1,10 , (2,3))  
print(arr) 

arr = np.random.randint(1,10 , (10,10))  
print(arr) 

print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)


[[6 5 8]
 [1 3 2]]
[[7 2 4 7 8 5 8 4 9 2]
 [1 4 6 3 3 8 1 7 2 1]
 [1 9 7 9 3 9 3 1 4 9]
 [7 4 8 1 2 5 7 4 1 7]
 [3 8 9 9 1 3 8 7 2 9]
 [6 9 7 4 1 9 9 9 8 1]
 [4 9 6 8 8 3 9 1 9 9]
 [3 5 6 8 9 5 9 4 7 5]
 [1 1 7 4 9 2 3 2 1 7]
 [5 9 2 4 9 3 4 2 9 8]]
<class 'numpy.ndarray'>
int64
(10, 10)
2
100


In [141]:
# np.random.uniform(start,end, shape) 

arr = np.random.uniform(50,100, (3,4))   
print(arr) 

arr = np.random.uniform(50,100, (3,1,2))   
print(arr) 

print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)


[[97.79743711 75.0830851  90.28629225 90.9813627 ]
 [95.58611062 71.11225416 92.58929285 72.15516359]
 [97.71167191 58.00056958 96.83043728 61.45766444]]
[[[51.44860601 69.72290517]]

 [[75.71866159 53.17086944]]

 [[83.54555071 61.70217023]]]
<class 'numpy.ndarray'>
float64
(3, 1, 2)
3
6


## array creation with range functions


In [159]:
# np.arange(first , end , step ) -> similar to range function 

arr = np.arange(1 , 10 ,1 )
mat = arr.reshape(3,3) 
print(arr) 
print(mat) 

arr = np.arange(1,10,1).reshape(3,3) 
print(arr) 

print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
(3, 3)
2
9


In [163]:
# np.linspace(start , end(included) , koita) 

arr = np.linspace(1, 10 ,10)
print(arr) 

arr = np.linspace(1, 10 ,15)
print(arr)

arr = np.linspace(4, 6 ,9)
print(arr)

print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.          1.64285714  2.28571429  2.92857143  3.57142857  4.21428571
  4.85714286  5.5         6.14285714  6.78571429  7.42857143  8.07142857
  8.71428571  9.35714286 10.        ]
[4.   4.25 4.5  4.75 5.   5.25 5.5  5.75 6.  ]
<class 'numpy.ndarray'>
float64
(9,)
1
9


In [170]:
# np.logspace(start , end(included) , koita ) 

arr = np.logspace(1 , 4 ,5) 
print(arr)
print("\n")

arr = np.logspace(0 , 4 ,5) 
print(arr)
print("\n")

arr = np.logspace(0 , 4 ,6, base =2) 
print(arr)

[   10.            56.23413252   316.22776602  1778.27941004
 10000.        ]


[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04]


[ 1.          1.74110113  3.03143313  5.27803164  9.18958684 16.        ]


## creating matrix for Linear algebra

In [171]:
diagonal_matrix = np.diag([1,2,3,4])

print(diagonal_matrix)
print('\n')
print(diagonal_matrix. shape)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


(4, 4)


In [177]:
# identity matrix 

identity_mat = np.eye(4)
print(identity_mat)
print(identity_mat.shape)


#np.eye(row , column,k) 

mat = np.eye(3,4)
print(mat)

mat = np.eye(3,4,-1)
print(mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


## indexing and slicing

In [195]:
#indexing 

print(arr1)
print(arr1[3])
print('\n')
print(arr2)
print("\n")

arr1[2] = 100 
print(arr1)
print("\n")

arr2[0][2]= 100
print(arr2)
print("\n")
print(arr2[1][2])


[  1   2 100   4   5   6]
4


[[  1   2 100   6]
 [  4   5   6   7]]


[  1   2 100   4   5   6]


[[  1   2 100   6]
 [  4   5   6   7]]


6


In [211]:
#slicing 
#1d = arr[start:end:step] 

print(arr1)
arr1_mod = arr1[1:4]
print(arr1_mod)

arr1_mod = arr1[1:4].copy()
print(arr1_mod)
arr1[1] = 2


arr1_mod[2] = 200
print(arr1_mod)
print(arr1)

[  1   2 100   4   5   6]
[  2 100   4]
[  2 100   4]
[  2 100 200]
[  1   2 100   4   5   6]


In [ ]:
#2d slicing 
# arr[ row_start : row_end : step , column_start : column_end : step ]

print(arr2)
print('\n') 

#getting a row 

row_0 = arr2[0:1 ,]

row_1= arr2[1: , ]

print(row_0)
print('\n')
print(row_1)
print('\n')

#getting a column 

col_0 = arr2[:: ,0:1]
col_1 = arr2[:,1:2] # 2 or 1  coloumn same

print(col_0)
print('\n')
print(col_1)
print('\n')

#getting a portion 


portion = arr2[:: , 0:2] 

print(portion)

[[  1   2 100   6]
 [  4   5   6   7]]


[[  1   2 100   6]]


[[4 5 6 7]]


[[1]
 [4]]


[[2]
 [5]]


[[1 2]
 [4 5]]


## Advanced Indexing

In [212]:
lst = np.array([ 10 , 20 ,30 ,40 ]) 
values = lst[[0,3,1]]

print(values)

[10 40 20]


In [216]:
print(arr2)
print(arr2[[0,1] , [1,2]])

# boolean kono kichu diye

arr2[arr2>2] = 0 

print(arr2)

[[  1   2 100   6]
 [  4   5   6   7]]
[2 6]
[[1 2 0 0]
 [0 0 0 0]]


In [217]:
print(arr2)

[[1 2 0 0]
 [0 0 0 0]]


In [220]:
arr  = np.array([[10,20,30] , [100,200,300] ] )

# iteration 

for i in arr3:
    for j in i:
        print(j)


print(arr3)
for i in np.nditer(arr3):
    print(i)

[1 2 3]
[4 5 6]
[1 2 3]
[4 5 6]
[1 2 3]
[4 5 6]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
1
2
3
4
5
6
1
2
3
4
5
6
1
2
3
4
5
6


Quiz

In [224]:
arr = np.array([1, 2, 3])
print(arr.ndim)


1


In [225]:
arr = np.full((2,2), np.inf)
print(arr)

[[inf inf]
 [inf inf]]


In [226]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr[1:4] = 0
print(arr)


[1 0 0 0 5]
