In [4]:
%pip install --default-timeout=1000 torch

Note: you may need to restart the kernel to use updated packages.


In [5]:
import torch
print(torch.__version__)



2.11.0+cu130


In [6]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Device name {torch.cuda.get_device_name(0)}")
else:
    print("GPU is not available")

GPU is not available


Creating Tensors

In [7]:
a = torch.empty(2, 3)
print(a)

tensor([[2.6919e-40, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 3.4797e-41, 0.0000e+00]])


In [8]:
type(a)

torch.Tensor

In [9]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [11]:
torch.rand(2, 3)

tensor([[0.6909, 0.3463, 0.5742],
        [0.8999, 0.9607, 0.1169]])

In [12]:
torch.manual_seed(100)
torch.rand(2, 3)


tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [13]:
torch.tensor([ [1, 2, 3], [4, 5, 6] ])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [15]:
torch.arange(0, 10, 1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:

torch.linspace(1, 10, 10)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

tensors Shape

In [17]:
x = torch.tensor([ [1, 2, 3], [4, 5, 6] ])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [18]:
x.shape

torch.Size([2, 3])

In [19]:
torch.empty_like(x)

tensor([[855601468,         0,        64],
        [      112,    210444,        64]])

In [20]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [21]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [23]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

Data Types

In [28]:
x.dtype

torch.int64

In [29]:
torch.tensor([1.0,2.0,3.0,4.0],dtype=torch.int32)

tensor([1, 2, 3, 4], dtype=torch.int32)

In [30]:
torch.tensor([1.0,2.0,3.0,4.0])


tensor([1., 2., 3., 4.])

In [33]:
X=x.to(torch.float32)

In [34]:
X.dtype

torch.float32

Math Scaler Operations

In [36]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [37]:
x+2

tensor([[3, 4, 5],
        [6, 7, 8]])

In [38]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [39]:
x-2

tensor([[-1,  0,  1],
        [ 2,  3,  4]])

In [40]:
x*2

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])

In [41]:
x/2

tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])

In [42]:
#floor

x=x*100

In [43]:
x//3

tensor([[ 33,  66, 100],
        [133, 166, 200]])

In [44]:
x**2

tensor([[ 10000,  40000,  90000],
        [160000, 250000, 360000]])

In [45]:
x%2

tensor([[0, 0, 0],
        [0, 0, 0]])

Math Element Wise Operation

In [46]:
a=torch.rand(2,3)
b=torch.rand(2,3)

In [55]:
b

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])

In [52]:
a+b

tensor([[0.9357, 1.0899, 0.5967],
        [1.7253, 1.5526, 1.7335]])

In [50]:
a-b

tensor([[ 0.4879,  0.4852,  0.2399],
        [ 0.0776,  0.4411, -0.2205]])

In [56]:
c=torch.tensor([-1,-2,-3,-4])

In [57]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [58]:
c=torch.tensor([1,2,3,4])

In [59]:
torch.neg(c)

tensor([-1, -2, -3, -4])

In [61]:
d=torch.tensor([1.2,2.6,3.9,4.3])

In [62]:
torch.round(d)

tensor([1., 3., 4., 4.])

In [63]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [64]:
torch.clamp(d,min=6,max=10)

tensor([6., 6., 6., 6.])

Math Reduction Operations

In [70]:
e= torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)

In [71]:
e

tensor([[7., 0., 0.],
        [9., 5., 7.]])

In [76]:
torch.sum(e)

tensor(28.)

In [77]:
torch.sum(e,dim=0) # column wise sum

tensor([16.,  5.,  7.])

In [78]:
torch.sum(e,dim=1) # row wise sum

tensor([ 7., 21.])

In [79]:
torch.mean(e)

tensor(4.6667)

In [80]:
torch.mean(e,dim=0)

tensor([8.0000, 2.5000, 3.5000])

In [81]:
torch.median(e)

tensor(5.)

In [82]:
# max and min

torch.min(e)

tensor(0.)

In [83]:
torch.max(e)

tensor(9.)

In [84]:
torch.prod(e)

tensor(0.)

In [85]:
torch.std(e)

tensor(3.8297)

In [86]:
torch.var(e)

tensor(14.6667)

In [87]:
# argmin ,argmax

torch.argmax(e)

tensor(3)

In [88]:
torch.argmin(e)

tensor(1)

Math matrix opertions

In [89]:
f = torch.randint(low=0, high=10, size=(2, 3))
g = torch.randint(low=0, high=10, size=(3, 2))

In [90]:
f

tensor([[3, 9, 4],
        [0, 5, 7]])

In [91]:
g

tensor([[5, 9],
        [9, 7],
        [5, 9]])

In [92]:
torch.matmul(f, g)

tensor([[116, 126],
        [ 80,  98]])

In [95]:
# Dot Product 

vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

In [96]:
torch.dot(vector1, vector2)

tensor(11)

In [97]:
f.shape

torch.Size([2, 3])

In [98]:
torch.transpose(f, 0, 1)

tensor([[8, 9],
        [9, 2],
        [7, 6]])

In [99]:
h = torch.randint(size=(3, 3), low=0, high=10, dtype=torch.float32)

In [100]:
torch.det(h)

tensor(185.)

In [101]:
torch.inverse(h)

tensor([[-0.0811, -0.0811,  0.2162],
        [ 0.2811,  0.0811, -0.2162],
        [-0.0649,  0.1351, -0.0270]])

Comparision Operations

In [102]:
i= torch.randint(size=(2,3),low=0,high=10)
j=torch.randint(size=(2,3),low=0,high=10)

In [103]:
i

tensor([[5, 0, 6],
        [4, 0, 8]])

In [104]:
j

tensor([[4, 7, 2],
        [3, 8, 5]])

In [105]:
# geneather than 
i>j

tensor([[ True, False,  True],
        [ True, False,  True]])

In [106]:
# less than
i<j

tensor([[False,  True, False],
        [False,  True, False]])

In [107]:
# equal to

i==j

tensor([[False, False, False],
        [False, False, False]])

In [108]:
# not equal to
i!=j

tensor([[True, True, True],
        [True, True, True]])

Special Functions


In [109]:
k= torch.tensor([10,20,30])
k

tensor([10, 20, 30])

In [110]:
torch.log(k)

tensor([2.3026, 2.9957, 3.4012])

In [111]:
torch.exp(k)

tensor([2.2026e+04, 4.8517e+08, 1.0686e+13])

In [112]:
torch.sqrt(k)

tensor([3.1623, 4.4721, 5.4772])

In [113]:
torch.sigmoid(k)

tensor([1.0000, 1.0000, 1.0000])

In [115]:
torch.relu(k)

tensor([10, 20, 30])

Inplace operations

In [116]:
a=torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [117]:
b=a+5
b

tensor([6, 7, 8])

In [118]:
m= torch.rand(2,3)
n=torch.rand(2,3)

In [119]:
m

tensor([[0.9605, 0.3271, 0.0103],
        [0.9516, 0.2855, 0.2324]])

In [120]:
n

tensor([[0.9141, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])

In [121]:
m.add_(n)

tensor([[1.8746, 1.0939, 0.1762],
        [1.3909, 0.5098, 1.1259]])

In [122]:
torch.relu_(m)

tensor([[1.8746, 1.0939, 0.1762],
        [1.3909, 0.5098, 1.1259]])

In [123]:
m.relu_()

tensor([[1.8746, 1.0939, 0.1762],
        [1.3909, 0.5098, 1.1259]])

In [ ]:
import torch

data = torch.tensor(
    [
        [2,3,3],
        [5,6,4],
        [7,8,5]
    ]
)
data

tensor([[2, 3, 3],
        [5, 6, 4],
        [7, 8, 5]])

In [ ]:
X = data[:,0:2].float()
y = data[:,2].float()

In [ ]:
X

tensor([[2., 3.],
        [5., 6.],
        [7., 8.]])

In [ ]:
y

tensor([3., 4., 5.])

# Weight Initialization

In [ ]:
# w = 1, b = 0

def initialize_parameters():
  parameters = {}

  parameters['W1'] = torch.ones( (2,2) ) * 0.1
  parameters['b1'] = torch.zeros( (2,1) )


  parameters['W2'] = torch.ones( (2,1) ) * 0.1

  parameters['b2'] = torch.zeros( (1,1) )

  return parameters



In [ ]:
initialize_parameters()

{'W1': tensor([[0.1000, 0.1000],
         [0.1000, 0.1000]]),
 'b1': tensor([[0.],
         [0.]]),
 'W2': tensor([[0.1000],
         [0.1000]]),
 'b2': tensor([[0.]])}

# Better way

In [ ]:
def initialize_parameters(layer_dims):
  torch.manual_seed(3)
  parameters = {}
  L = len(layer_dims)

  for l in range(1,L):
    parameters["W" + str(l)] = torch.ones( (layer_dims[l-1], layer_dims[l]))*0.1
    parameters["b" + str(l)] = torch.zeros( (layer_dims[l], 1))

  return parameters




In [ ]:
initialize_parameters( [2,2,1] )

{'W1': tensor([[0.1000, 0.1000],
         [0.1000, 0.1000]]),
 'b1': tensor([[0.],
         [0.]]),
 'W2': tensor([[0.1000],
         [0.1000]]),
 'b2': tensor([[0.]])}

# Forward Propagation

In [ ]:
def linear_forward( A_prev, W, b ) :
  Z = torch.matmul( W.T , A_prev ) + b
  return Z


In [ ]:
def L_layer_forward(X,parameters):
  A = X
  L = len(parameters)//2

  for l in range(1,L+1):
    A_prev = A

    wl = parameters['W' + str(l)]
    bl = parameters['b' + str(l)]
    A = linear_forward( A_prev, wl, bl )

  return A, A_prev





In [ ]:
X

tensor([[2., 3.],
        [5., 6.],
        [7., 8.]])

In [ ]:
params = initialize_parameters([2,2,1])
X_sample = X[0].reshape(2,1)
y_hat, A1 = L_layer_forward(X_sample,params)


In [ ]:
y_hat

tensor([[0.1000]])

In [ ]:
A1

tensor([[0.5000],
        [0.5000]])

In [ ]:
(y-y_hat) ** 2

tensor([[ 8.4100, 15.2100, 24.0100]])

In [ ]:
params

{'W1': tensor([[0.1909, 0.2086],
         [0.1923, 0.2103]]),
 'b1': tensor([[0.0177],
         [0.0180]]),
 'W2': tensor([[0.2541],
         [0.2624]]),
 'b2': tensor([[0.1032]])}

In [ ]:
params['W2']

tensor([[0.2541],
        [0.2624]])

In [ ]:
params['W2'][0,0]

tensor(0.2541)

In [ ]:
params['W2'][1,0]

tensor(0.2624)

In [ ]:
A1

tensor([[2.6973],
        [2.9377]])

In [ ]:
def update_parameters(parameters, y, y_hat, A1, X, lr=0.001):

    err_signal = 2 * (y - y_hat)

     #  Save OLD W2 values before updating
    W2_00_old = parameters['W2'][0, 0].item()
    W2_10_old = parameters['W2'][1, 0].item()

    # Update Layer 2




    parameters['W2'][0, 0] += lr * err_signal * A1[0, 0]
    parameters['W2'][1, 0] += lr * err_signal * A1[1, 0]
    parameters['b2'][0, 0] += lr * err_signal #


    parameters['W1'][0, 0] += lr * err_signal * parameters['W2'][0, 0] * X[0, 0]
    parameters['W1'][0, 1] += lr * err_signal * parameters['W2'][0, 0] * X[1, 0]
    parameters['b1'][0, 0] += lr * err_signal * parameters['W2'][0, 0]

    parameters['W1'][1, 0] += lr * err_signal * parameters['W2'][1, 0] * X[0, 0]
    parameters['W1'][1, 1] += lr * err_signal * parameters['W2'][1, 0] * X[1, 0]
    parameters['b1'][1, 0] += lr * err_signal * parameters['W2'][1, 0]

    return parameters

In [ ]:
# using loop



params = initialize_parameters([2, 2, 1])
epochs = 5

for i in range(epochs):
    epoch_loss = 0
    for j in range(X.shape[0]):
        # Prepare sample
        X_sample = X[j].reshape(2, 1)
        y_sample = y[j]

        # Forward
        y_hat, A1 = L_layer_forward(X_sample, params)
        y_hat_scalar = y_hat[0, 0]

        # Update
        params = update_parameters(params, y_sample, y_hat_scalar, A1, X_sample)

        # Loss calculation
        loss = (y_sample - y_hat_scalar) ** 2
        epoch_loss += loss.item()

    print(f"Epoch - {i+1} Loss - {epoch_loss / X.shape[0]}")

Epoch - 1 Loss - 14.67866039276123
Epoch - 2 Loss - 13.701451301574707
Epoch - 3 Loss - 12.494118690490723
Epoch - 4 Loss - 11.040447076161703
Epoch - 5 Loss - 9.366330782572428
